name: flutter_open_app_store
description: A new Flutter plugin.
version: 0.0.1
author: StephenNeverMore(stephen0zhu@gmail.com)
homepage: https://github.com/StephenNeverMore

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: org.stephen.flutter_open_app_store
    pluginClass: FlutterOpenAppStorePlugin
